### Send POST request with json body
POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "name": "Carton of milk"
}

### Send POST request with json body
POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "name": "1Kg of Coffee"
}

### GET request with a header
GET http://localhost:8080/api/v1/items
Accept: application/json

### Send POST request with json body
PUT http://localhost:8080/api/v1/items/1?itemName="1l Carton of milk"
Content-Type: application/json

### Send POST request with json body
POST http://localhost:8080/api/v1/items/1/states
Content-Type: application/json

{
  "name": "1Kg of Coffee",
  "amount": 1
}

### GET request with a header
GET http://localhost:8080/api/v1/items/1/states
Accept: application/json