function moment = inverse_dynamic_2DoF_calculate_moment(mass, ...
                                                        arm_len, ...
                                                        pos, ...
                                                        speed, ...
                                                        accel)
    [Mass, Coriolise] = calculate_M_C(mass, arm_len, pos, speed);
    
    moment = Mass * accel + Coriolise * speed;
end