% 
% return format:
%   arm1 [at1, at2, at3, ...]
%   arm2 [at1, at2, at3, ...]
function [moment] = run_inverse_dynamic_2DoF_calculate_moment(...
                                                        arm_mass, ...
                                                        arm_length, ...
                                                        pos, speed, accel)
    iterations = size(pos, 2);

    moment = zeros(2, iterations);
    for i = 1:iterations
        moment(:, i) = inverse_dynamic_2DoF_calculate_moment(...
                                                  arm_mass, arm_length, ...
                                                  pos(:, i), ... 
                                                  speed(:, i), ... 
                                                  accel(:, i));
    end
end